import type { MediaSection } from "../types/media.types";

export const MCU_PHASES: MediaSection[] = [
  {
    name: "Avengers Assemble",
    media: [
      {
        id: "captain-america-the-first-avenger",
        name: "Captain America: The First Avenger",
        image: "/images/mcu/avengers-assemble/captain-america-the-first-avenger.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "agent-carter-oneshot",
        name: "Agent Carter",
        subLine: "Oneshot",
        image: "/images/mcu/avengers-assemble/agent-carter-oneshot.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "agent-carter-seasons",
        name: "Agent Carter",
        subLine: "Season 1 & 2",
        image: "/images/mcu/avengers-assemble/agent-carter_seasons.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "captain-marvel",
        subLine: "Mid-credit scene after Infinity War",
        name: "Captain Marvel",
        image: "/images/mcu/avengers-assemble/captain-marvel.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "iron-man",
        name: "Iron Man",
        image: "/images/mcu/avengers-assemble/iron_man_1.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "iron-man-2",
        name: "Iron Man 2",
        image: "/images/mcu/avengers-assemble/iron_man_2.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "incredible-hulk",
        name: "The Incredible Hulk",
        image: "/images/mcu/avengers-assemble/incredible_hulk.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "the-consultant",
        name: "The Consultant",
        subLine: "one-shot",
        image: "/images/mcu/avengers-assemble/consultant.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "a-funny-thing-happened-on-the-way-to-thor-s-hammer",
        name: "A Funny Thing Happened on the Way to Thor's Hammer",
        subLine: "one-shot",
        image: "/images/mcu/avengers-assemble/funny_thing.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "thor",
        name: "Thor",
        image: "/images/mcu/avengers-assemble/thor.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "the-avengers",
        name: "The Avengers",
        image: "/images/mcu/avengers-assemble/avengers.webp",
        watched: false,
        comicSize: "full",
      },
    ],
  },
  {
    name: "Age of Ultron",
    media: [
      {
        id: "item-47",
        name: "Item 47",
        subLine: "one-shot",
        image: "/images/mcu/age-of-ultron/item_47.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-1-episodes-1-7",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 1, episodes 1-7",
        image: "/images/mcu/age-of-ultron/agents_of_shield.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "thor-the-dark-world",
        name: 'Thor: The Dark World',
        image: "/images/mcu/age-of-ultron/thor_dark_world.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-1-episodes-8-16",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 1, episodes 8-16",
        image: "/images/mcu/age-of-ultron/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "iron-man-3",
        name: "Iron Man 3",
        image: "/images/mcu/age-of-ultron/iron_man_3.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "all-hail-the-king",
        name: "All Hail the King",
        subLine: "one-shot",
        image: "/images/mcu/age-of-ultron/all_hail_the_king.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "captain-america-the-winter-soldier",
        name: "Captain America: The Winter Soldier",
        image: "/images/mcu/age-of-ultron/captain_america_winter_soldier.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-1-episodes-17-22",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 1, episodes 17-22",
        image: "/images/mcu/age-of-ultron/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "guardians-of-the-galaxy",
        name: 'Guardians of the Galaxy',
        image: "/images/mcu/age-of-ultron/guardians_of_the_galaxy.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "guardians-of-the-galaxy-vol-2",
        name: "Guardians of the Galaxy Vol. 2",
        image: "/images/mcu/age-of-ultron/guardians_of_the_galaxy_vol2.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "i-am-groot",
        name: "I Am Groot",
        subLine: "Season 1&2",
        image: "/images/mcu/age-of-ultron/i_am_groot.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "daredevil-season-1",
        name: "Daredevil",
        subLine: "Season 1",
        image: "/images/mcu/age-of-ultron/daredevil.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-2-episodes-1-10",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 2, episodes 1-10",
        image: "/images/mcu/age-of-ultron/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "jessica-jones-season-1",
        name: "Jessica Jones",
        subLine: "Season 1",
        image: "/images/mcu/age-of-ultron/jessica_jones.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-2-episodes-11-19",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 2, episodes 11-19",
        image: "/images/mcu/age-of-ultron/agents_of_shield.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "avengers-age-of-ultron",
        name: "Avengers: Age of Ultron",
        image: "/images/mcu/age-of-ultron/avengers_age_of_ultron.webp",
        watched: false,
        comicSize: "full",
      },
    ],
  },
  {
    name: "Civil War",
    media: [
      {
        id: "agents-of-s-h-i-e-l-d-season-2-episodes-20-22",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 2, episodes 20-22",
        image: "/images/mcu/civil-war/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "daredevil-season-2-episodes-1-4",
        name: "Daredevil",
        subLine: "Season 2, episodes 1-4",
        image: "/images/mcu/civil-war/daredevil.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "luke-cage-season-2-episodes-1-4",
        name: "Luke Cage",
        subLine: "Season 1, episodes 1-4",
        image: "/images/mcu/civil-war/luke_cage.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "daredevil-season-2-episodes-5-11",
        name: "Daredevil",
        subLine: "Season 2, episodes 5-11",
        image: "/images/mcu/civil-war/daredevil.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "luke-cage-season-1-episodes-5-8",
        name: "Luke Cage",
        subLine: "Season 1, episodes 5-8",
        image: "/images/mcu/civil-war/luke_cage.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "daredevil-season-2-episodes-12-13",
        name: "Daredevil",
        subLine: "Season 2, episodes 12-13",
        image: "/images/mcu/civil-war/daredevil.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "luke-cage-season-1-episodes-9-13",
        name: "Luke Cage",
        subLine: "Season 1, episodes 9-13",
        image: "/images/mcu/civil-war/luke_cage.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "ant-man",
        name: "Ant-Man",
        image: "/images/mcu/civil-war/ant_man.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-3-episodes-1-19",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 3, episodes 1-19",
        image: "/images/mcu/civil-war/agents_of_shield.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "iron-fist-season-1",
        name: "Iron Fist",
        subLine: "Season 1",
        image: "/images/mcu/civil-war/iron_fist.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "captain-america-civil-war",
        name: "Captain America: Civil War",
        image: "/images/mcu/civil-war/civil_war.webp",
        watched: false,
        comicSize: "full",
      },
    ]
  },
  {
    name: 'Infinity War',
    media: [
      {
        id: "team-thor",
        name: "Team Thor",
        subLine: "one-shot",
        image: "/images/mcu/infinity-war/team_thor.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "team-thor-part-2",
        name: "Team Thor: Part 2",
        subLine: "one-shot",
        image: "/images/mcu/infinity-war/team_thor_2.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "black-widow",
        name: "Black Widow",
        subLine: "Watch credits scene after Endgame",
        image: "/images/mcu/infinity-war/black-widow.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-3-episodes-20-22",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 3, episodes 20-22",
        image: "/images/mcu/infinity-war/agents_of_shield.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "the-defenders-season-1",
        name: "The Defenders",
        subLine: "Season 1",
        image: "/images/mcu/infinity-war/defenders.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-4-episodes-1-6",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 4, episodes 1-6",
        image: "/images/mcu/infinity-war/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "doctor-strange",
        name: "Doctor Strange",
        image: "/images/mcu/infinity-war/doctor_strange.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "black-panther",
        name: "Black Panther",
        image: "/images/mcu/infinity-war/black_panther.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-4-episodes-7-8",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 4, episodes 7-8",
        image: "/images/mcu/infinity-war/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "agents-of-s-h-i-e-l-d-slingshot-season-1",
        name: "Agents of S.H.I.E.L.D.: Slingshot",
        subLine: "Season 1, episodes 1-6",
        image: "/images/mcu/infinity-war/agents_of_shield_slingshot.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-4-episodes-9-22",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 4, episodes 9-22",
        image: "/images/mcu/infinity-war/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "spider-man-homecoming",
        name: "Spider-Man: Homecoming",
        image: "/images/mcu/infinity-war/spider-man_homecoming.webp",
        watched: false,
        comicSize: "full",
      },
      {
        id: "thor-ragnarok",
        name: "Thor: Ragnarok",
        image: "/images/mcu/infinity-war/thor_ragnarok.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "team-darryl",
        name: "Team Darryl",
        subLine: "one-shot",
        image: "/images/mcu/infinity-war/team_darryl.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "inhumans-season-1",
        name: "Inhumans",
        subLine: "Season 1",
        image: "/images/mcu/infinity-war/inhumans.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "the-punisher-season-1",
        name: "The Punisher",
        subLine: "Season 1",
        image: "/images/mcu/infinity-war/punisher.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "runaways-season-1",
        name: "Runaways",
        subLine: "Season 1",
        image: "/images/mcu/infinity-war/runaways.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-5-episodes-1-10",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 5, episodes 1-10",
        image: "/images/mcu/infinity-war/agents_of_shield.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "jessica-jones-season-2",
        name: "Jessica Jones",
        subLine: "Season 2",
        image: "/images/mcu/infinity-war/jessica_jones.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-5-episodes-11-18",
        name: "Agents of S.H.I.E.L.D.",
        subLine: "Season 5, episodes 11-18",
        image: "/images/mcu/infinity-war/agents_of_shield.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "cloak-and-dagger-season-1-2",
        name: "Cloak & Dagger",
        subLine: "Season 1 & 2",
        image: "/images/mcu/infinity-war/cloak_and_dagger.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "luke-cage-season-2",
        name: "Luke Cage",
        subLine: "Season 2",
        image: "/images/mcu/infinity-war/luke_cage.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "iron-fist-season-2",
        name: "Iron Fist",
        subLine: "Season 2",
        image: "/images/mcu/infinity-war/iron_fist.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "daredevil-season-3",
        name: "Daredevil",
        subLine: "Season 3",
        image: "/images/mcu/infinity-war/daredevil.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "runaways-season-2",
        name: "Runaways",
        subLine: "Season 2",
        image: "/images/mcu/infinity-war/runaways.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "the-punisher-season-2",
        name: "The Punisher",
        subLine: "Season 2",
        image: "/images/mcu/infinity-war/punisher.webp",
        watched: false,
        comicSize: "half",
      },
      {
        id: "jessica-jones-season-3",
        name: "Jessica Jones",
        subLine: "Season 3",
        image: "/images/mcu/infinity-war/jessica_jones.webp",
        watched: false,
        comicSize: "third",
      },
      {
        id: "ant-man-and-the-wasp",
        name: "Ant-Man and the Wasp",
        subLine: "Watch credits scene after Infinity War",
        image: "/images/mcu/infinity-war/ant_man_and_the_wasp.webp",
        watched: false,
        comicSize: "two-thirds",
      },
      {
        id: "avengers-infinity-war",
        name: "Avengers: Infinity War",
        image: "/images/mcu/infinity-war/infinity_war.webp",
        watched: false,
        comicSize: "full",
      },
    ]
  }, {
    name: 'Endgame',
    media: [
      {
        id: "agents-of-s-h-i-e-l-d-season-5-episodes-19-22",
        name: 'Agents of S.H.I.E.L.D.',
        subLine: 'Season 5, episodes 19-22, concurrent with Infinity War',
        image: "/images/mcu/endgame/agents_of_shield.webp",
        watched: false,
        comicSize: 'third'
      },
      {
        id: "agents-of-s-h-i-e-l-d-season-6-7",
        name: 'Agents of S.H.I.E.L.D.',
        subLine: 'Season 6&7, during Endgame\'s 5-year time jump',
        image: "/images/mcu/endgame/agents_of_shield.webp",
        watched: false,
        comicSize: 'third'
      },
      {
        id: "runaways-season-3",
        name: "Runaways",
        subLine: "Season 3 (post-Snap)",
        image: "/images/mcu/endgame/runaways.webp",
        watched: false,
        comicSize: 'third'
      },
      {
        id: 'avengers-end-game',
        name: 'Avengers Endgame',
        image: '/images/mcu/endgame/end-game.webp',
        watched: false,
        comicSize: 'full'
      }
    ]
  }, {
    name: 'Multiverse',
    media: [
      {
        id: "loki-season-1-2",
        name: 'Loki',
        subLine: 'Season 1&2',
        image: "/images/mcu/multiverse/loki.webp",
        watched: false,
        comicSize: 'half'
      },
      {
        id: "what-if-season-1-2-3",
        name: 'What If...?',
        subLine: 'Season 1&2&3',
        image: "/images/mcu/multiverse/what-if.webp",
        watched: false,
        comicSize: 'half'
      },
      {
        id: "wanda-vision-season-1",
        name: "WandaVision",
        subLine: "Season 1",
        image: "/images/mcu/multiverse/wandavision.webp",
        watched: false,
        comicSize: 'third'
      },
      {
        id: 'deadpool-wolverine',
        name: 'Deadpool & Wolverine',
        image: '/images/mcu/multiverse/deadpool_and_wolverine.webp',
        watched: false,
        comicSize: 'two-thirds'
      },
      {
        id: 'shang-chi-and-the-legend-of-the-ten-rings',
        name: 'Shang-Chi and the Legend of the Ten Rings',
        image: '/images/mcu/multiverse/shang_chi.webp',
        watched: false,
        comicSize: 'full'
      },
      {
        id: 'falcon-and-the-winter-soldier',
        name: 'The Falcon and the Winter Soldier',
        subLine: 'Season 1',
        image: '/images/mcu/multiverse/falcon_winter_soldier.webp',
        watched: false,
        comicSize: 'third'
      },
      {
        id: 'eternals',
        name: 'Eternals',
        image: '/images/mcu/multiverse/eternals.webp',
        watched: false,
        comicSize: 'two-thirds'
      },
      {
        id: 'spider-man-far-from-home',
        name: 'Spider-Man: Far From Home',
        image: '/images/mcu/multiverse/spider-man_far_from_home.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'spider-man-no-way-home',
        name: 'Spider-Man: No Way Home',
        image: '/images/mcu/multiverse/spider-man_no_way_home.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'doctor-strange-in-the-multiverse-of-madness',
        name: 'Doctor Strange in the Multiverse of Madness',
        image: '/images/mcu/multiverse/doctor_strange_multiverse.webp',
        watched: false,
        comicSize: 'full'
      }
    ]
  }, {
    name: 'Brave New World',
    media: [
      {
        id: 'hawkeye',
        name: 'Hawkeye',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/hawkeye.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'moon-knight',
        name: 'Moon Knight',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/moon-knight.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'black-panther-wakanda-forever',
        name: 'Black Panther: Wakanda Forever',
        image: '/images/mcu/brave-new-world/black-panther_wakanda-forever.webp',
        watched: false,
        comicSize: 'full'
      },
      {
        id: 'echo',
        name: 'Echo',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/echo.webp',
        watched: false,
        comicSize: 'third'
      },
      {
        id: 'she-hulk-attorney-at-law',
        name: 'She-Hulk: Attorney at Law',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/she-hulk.webp',
        watched: false,
        comicSize: 'third'
      },
      {
        id: 'ms-marvel',
        name: 'Ms Marvel',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/ms_marvel.webp',
        watched: false,
        comicSize: 'third'
      },
      {
        id: 'thor-love-and-thunder',
        name: 'Thor: Love and Thunder',
        image: '/images/mcu/brave-new-world/thor-love-and-thunder.webp',
        watched: false,
        comicSize: 'full'
      },
      {
        id: 'werewolf-by-night',
        name: 'Werewolf by Night',
        subLine: 'Holiday Special',
        image: '/images/mcu/brave-new-world/werewolf-by-night.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'guardians-of-the-galaxy-holiday-special',
        name: 'The Guardians of the Galaxy Holiday Special',
        subLine: 'Holiday Special',
        image: '/images/mcu/brave-new-world/guardians-of-the-galaxy-holiday-special.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'ant-man-and-the-wasp-quantumania',
        name: 'Ant-Man and the Wasp: Quantumania',
        image: '/images/mcu/brave-new-world/ant-man-quantumania.webp',
        watched: false,
        comicSize: 'full'
      },
      {
        id: 'guardians-of-the-galaxy-vol-3',
        name: 'Guardians of the Galaxy Vol 3',
        image: '/images/mcu/brave-new-world/guardians-of-the-galaxy-vol-3.webp',
        watched: false,
        comicSize: 'two-thirds'
      },
      {
        id: 'secret-invasion',
        name: 'Secret Invasion',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/secret-invasion.webp',
        watched: false,
        comicSize: 'third'
      },
      {
        id: 'the-marvels',
        name: 'The Marvels',
        image: '/images/mcu/brave-new-world/the-marvels.webp',
        watched: false,
        comicSize: 'full'
      },
      {
        id: 'agatha-all-along',
        name: 'Agatha All Along',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/agatha-all-along.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'daredevil-born-again',
        name: 'Daredevil: Born Again',
        subLine: 'Season 1',
        image: '/images/mcu/brave-new-world/daredevil-born-again.webp',
        watched: false,
        comicSize: 'half'
      },
      {
        id: 'captain-america-brave-new-world',
        name: 'Captain America: Brave New World',
        image: '/images/mcu/brave-new-world/captain-america-brave-new-world.webp',
        watched: false,
        comicSize: 'full'
      },
    ],
  }
];
